### ISSUE TITLE
Developer Environment and Tools

### ISSUE THREAD

**Issue by ninabreznik** [ESova/esova.github.io#1]
Possibilities we have:
- [ ] REMOTE SERVER with installed Linux
- requires high speed internet (also at student's home)
- high costs (we would have to create 1 virtual machine per student)
- [ ] EXISTING TOOLS (Koding.com, C9.io)
- in theory very good option because it offers exactly this - remote computer with preinstalled developer environment
- never tested for full stack development so far
- [x] REAL ENVIRONMENT
- Tutorial for setting up environment on student's local computer
- adapt tutorials for Linux, IOS and Windows
- advantage - this is teaching them for how they will really code in the future (real environment)

**Comment by ninabreznik** [comment]
I think the best option would be the third one - real environment and we will take care kids get all necessary screencasts to setup the environments with no hassle.

**Comment by MatijaDjumic** [comment]
Completely agree with the third option.

**Comment by serapath** [comment]
+1
