### ISSUE TITLE
[SPRINT 0]: APP Specification

### ISSUE THREAD

**Issue by ninabreznik** [ESova/esova.github.io#2]
## App

**INSPIRATION**
- Khan Academy
  - https://www.youtube.com/watch?v=jsDOHy8pHTg
- Coursera 
  - https://www.codecademy.com/courses/web-beginner-en-HZA3b/2/2?curriculum_id=50579fb998b470000202dc8b
  - https://www.codecademy.com/en/skills/make-a-website
- Rails Casts
  - http://railscasts.com/episodes/310-getting-started-with-rails?autoplay=true
- Open Tech School
  - http://opentechschool.github.io/js-beginners-4h-workshop-1/page1.html
- Rails Girls 
  - http://mislav.uniqpath.com/poignant-guide/book/chapter-3.html

**PAGE**
- access - each student receives a code (signup only with the code) (how to generate codes? manually copy-paste them and then app checks if code is there or not?)
- Table of Content - Three main chapters (1.Theory, 2.Tools, 3.Portfolio)
  - (left side of page)
- Screencasts (tutorial for building a simple app) *
  - (center top area of the page)
- Snippets of Code (copy-paste) *
  - (center bottom of the page)
- E-Owl Avatar Wizard (explaining the screencast; we prepare english version, you do voiceover)
  - (right bottom of the page)
- Badges (just some basic badges - later we can maybe gamify the whole thing, but wouldn't spend too much time with it for MVP)
  - (top right of the page)
- Signup/Login
- Able to handle 10.000 views/day
- 1.chapter - Theory 
  - explaination then 
  - student repeats by himself (program checks if answer is correct (yes or no))

**CHAT**
- Each step of tutorial in any chapter has a separate repository (folder) and has it's own Gitter chat and esova github repository
- When in trouble under each step of tutorial you just click a link to the chat and talk to other students (and moderator - community manager - support)
  - => integrate gitter chat (iframe? api? ...)
- Support - if the problem is too hard (we will put lots of afford to minimize that, support can even fix the problem via TeamViewer)

**DURATION**
- 10 months
- 70h all together

**CODE**
- pushed to Github *
- deployed to live version via Github pages *

**COMMUNITY**
- find local geeks who would volunteer/run weekly workshops 
- program for learners is on ESova, they can just be around (but it's not necessary, because it's self directed learning) if kids need help

[*]

>  REAL ENVIRONMENT
> Tutorial for setting up environment on student's local computer
> adapt tutorials for Linux, IOS and Windows
> advantage - this is teaching them for how they will really code in the future (real environment)

**Comment by MatijaDjumic** [comment]
Alright - agree with the workflow.

**Comment by serapath** [comment]
I think I need to put some more details into this and estimate how long certain parts would take to be implemented. I'll try to do that in the next days, but because I'm busy with projects I'm going to finish soon, I can probably only start in the beginning of september

**Comment by MatijaDjumic** [comment]
Deal - we will get the official confirmation after the Sabac event anyway, so it fits that schedule.

**Comment by serapath** [comment]
See [Esova/Specification](https://github.com/ESova/Concept/tree/master/SPECIFICATION)

**Comment by MatijaDjumic** [comment]
Thanks, just 1 question - what is my exact action step regarding this
specification?

On Fri, Oct 23, 2015 at 6:50 PM, Alexander Praetorius <
notifications@github.com> wrote:

> See Esova/Specification
> https://github.com/ESova/Concept/tree/master/SPECIFICATION
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ESova/Concept/issues/2#issuecomment-150631032.

## 

+381 65 _25 45 461_
  Chief Operating Officer

**Comment by ninabreznik** [comment]
Hey, Petar needed work-in-progess update, so we opened the thing. We are otherwise making a ppt specification that has to go to the developers to give time/costs estimation for creating the app.

**Comment by serapath** [comment]
Link: https://docs.google.com/presentation/d/1NCnyTAl7sy4dzcx7ut4FGq9R_MN2sA8DBxS7y9zrLOo/edit#slide=id.ge584f217c_1_61

**Comment by MatijaDjumic** [comment]
Super cool, let me know if u need anything from my side!

On Sat, Oct 24, 2015 at 12:50 AM, Alexander Praetorius <
notifications@github.com> wrote:

> Link:
> https://docs.google.com/presentation/d/1NCnyTAl7sy4dzcx7ut4FGq9R_MN2sA8DBxS7y9zrLOo/edit#slide=id.ge584f217c_1_61
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ESova/Concept/issues/2#issuecomment-150710422.

## 

+381 65 _25 45 461_
  Chief Operating Officer
