### ISSUE TITLE
Sabac Presentation

### ISSUE THREAD

**Issue by serapath** [ESova/esova.github.io#7]
# [Šabac event - 5.9. Saturday](https://docs.google.com/spreadsheets/d/1SsAkSKB2lU4CJ2-U1wD3ucSO8cncfIorYAh-hX8U_jg/edit#gid=0)
## Why: Workforce supply and demand analysis

``` javascript
/*
WHY (Problem, now)

    Statistics show:
    50-80% of all current jobs are at risk of being automated in the coming decade
    programming is the new literacy people need to know to utilize this automation

*/
```

> 1. Global and local workforce perspective - with the conclusion that we obviously lack IT talents  

...

> 1. We give a Serbian perspective of how many IT talents we actually lack - with clear data supporting this claim  

...

> 1. We clearly state the effect this project can have on the unemployment of Serbian young people - with clear data supporting this, their average incomes and the future of the Šabac region.  

...

> 1. Questions and answers after every presentation  

...
## How: implementation of the eSova project

``` javascript
/*
HOW (Solution, process)

It's possible to actually become a programmer and do something useful
in 1-2 years of intensive practice. An online curriculum,
where people go through a structured series of video tutorials and code examples,
which explain them step by step how to build a basic app will get them there.
Later they can modify and change this example app to something else
and continue their process.
*/
```

> 1. We go through the project timeline clearly stating the whole plan that leads to the full implementation of the project  

...

> 1. We clearly state and thus involve, the local IT influencers present there. Asking for their opinion and help during the implementation.  

...

> 1. Questions and answers section  

...
## What: the eSova webapp and development

``` javascript
/*
WHAT (Goal, future)

Coding/Programming is the literacy of the future!

Turning all kinds of people into literate people (programmers)
or at least give them enough understanding so that they can enhance their work skills
with a bit of programming and to have in general a better understanding of programming
and technology to be able to continue to learn and to be able to follow what's going on
in this world and how technology is shaping our future.
*/
```

> 1. Nina, Alex and guests tune in via skype to present all the details of the webapp.  

..

> 1. Questions and answers.  

...

**Comment by serapath** [comment]
# Materials
- **Coding in schools**
  - ...
- **Changing a profession**
  - ...
- **Women in tech**
  - http://www.brainpickings.org/2014/12/10/ada-lovelace-walter-isaacson-innovators/

**Connect with local influencers**
- after school private tutoring
- apply for local/remote jobs
- make protfolio
- make certificates (for local influencers)

**AUDIENCE**
- Teachers (with some "techy" background)

**PRESENTATION**
- http://slides.com/pricing

## WHY (Problem, now)

Statistics show:
50-80% of all current jobs are at risk of being automated in the coming decade
programming is the new literacy people need to know to utilize this automation
- **CHECK** http://www.npr.org/sections/money/2015/05/21/408234543/will-your-job-be-done-by-a-machine
- http://fortune.com/2015/05/20/here-are-the-jobs-automation-will-kill-next/
- http://thenextweb.com/shareables/2015/05/27/what-are-the-odds-of-losing-your-job-to-automation/
- http://www.bbc.com/future/story/20150805-will-machines-eventually-take-on-every-job

MORE JOB STATS:
- http://www.fastcoexist.com/3049619/why-companies-need-to-think-deeply-about-the-labor-implications-of-a-second-machine-age
- http://www.welt.de/wirtschaft/article140401411/Maschinen-koennten-18-Millionen-Arbeitnehmer-verdraengen.html
- **EVIDENCE** http://thenextweb.com/media/2011/04/18/robot-journalist-writes-a-better-story-than-human-sports-reporter/
- RESEARCH PAPER: http://www.oxfordmartin.ox.ac.uk/downloads/academic/The_Future_of_Employment.pdf

HOW TO PREPARE / THE FUTURE OF WORK:
- http://blog.fiverr.com/freelancing-new-normal/
- https://medium.com/end-homelessness/the-cure-for-homelessness-83ef0d621c71
- https://medium.com/end-homelessness/fighting-poverty-in-schools-b3417a99b4e3
- https://medium.com/end-homelessness/fighting-poverty-with-code-d1ed3ebd982d

**HOW DOES THIS FUTURE LOOK LIKE?**
- https://medium.com/javascript-scene/get-ready-for-the-future-f4cf7610b985
- **FUTURE (Burke):** https://www.youtube.com/watch?v=5mo_Ux_WzGw
- **ROBOTS (Humans Need Not Apply):** https://www.youtube.com/watch?t=54&v=7Pq-S557XQU
- **AI:** https://www.youtube.com/watch?v=UIWWLg4wLEY
- http://glitch.news/2015-08-27-ai-robot-that-learns-new-words-in-real-time-tells-human-creators-it-will-keep-them-in-a-people-zoo.html
- **ASSEMBLY ROBOT:** http://thenextweb.com/shareables/2015/05/25/meet-brett-the-berkeley-robotics-lab-creation-capable-of-learning/
- **DRONES:** https://www.youtube.com/watch?v=w2itwFJCgFQ
- **MATERIALS:** http://www.selfassemblylab.net/ProgrammableMaterials.php
- **CRYPTO LAW:** http://etherscripter.com/what_is_ethereum.html
- https://www.youtube.com/watch?v=nZEbnc5x-GI
- https://medium.com/javascript-scene/get-ready-for-the-future-f4cf7610b985
- **CRYPTO MONEY:** http://bitbybit.co/social-media-growth-hacking-bitcoin/best-bitcoin-infographics

OUTDATED SCHOOLS?
- http://techcrunch.com/2015/05/31/hard-core-career-advice-for-a-13-year-old/

**HOW DO OTHERS PREPARE?**
GREECE:
- http://money.cnn.com/2015/06/29/technology/greece-bitcoin/index.html

SCHOOL & PROGRAMMING
- UK: http://www.theguardian.com/technology/2014/sep/04/coding-school-computing-children-programming
- http://www.theguardian.com/technology/2014/sep/22/computing-bcs-uk-computing-curriculum
- FINNLAND (2016): http://yle.fi/uutiset/coding_soon_to_be_part_of_finnish_schoolchildrens_core_curriculum/7818567
- AUSTRALIA: http://www.smh.com.au/national/computer-science-reforms-to-test-teachers-skills-20140111-30nj4.html
- USA: https://code.org/
- http://www.codeforamerica.org/
- ESTONIA: http://ubuntulife.net/computer-programming-for-all-estonian-schoolchildren/
- http://www.wired.co.uk/news/archive/2012-09/05/estonia-kid-coding
- http://www.forbes.com/sites/parmyolson/2012/09/06/why-estonia-has-started-teaching-its-first-graders-to-code/
- http://www.nytimes.com/2014/03/24/world/europe/adding-coding-to-the-curriculum.html
- FRANCE: http://www.itworld.com/article/2696639/application-management/france-to-offer-programming-in-elementary-school.html

## WHAT (Goal, future)

Turning all kinds of people into programmers or at least give them enough understanding so that they can enhance their work skills with a bit of programming and to have in general a better understanding of programming and technology to be able to continue to learn and to be able to follow what's going on in this world and how technology is shaping our future

WHAT IS CODE?
- http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/

POPULARITY
- http://www.modulecounts.com/
- http://www.wired.com/2015/08/github-data-shows-changing-software-landscape/

NODE/JS/HTML/CSS
- https://strongloop.com/wp-content/uploads/2015/02/final-node-infographic-3-18-15v1.pdf
- LANGUAGE POPULARITY: http://githut.info/
- http://www.dataists.com/2010/12/ranking-the-popularity-of-programming-langauges/
- http://redmonk.com/sogrady/2015/07/01/language-rankings-6-15/
- http://redmonk.com/sogrady/2015/01/14/language-rankings-1-15/
- http://redmonk.com/sogrady/2014/06/13/language-rankings-6-14/#comment-1437856760
- https://psdtowp.net/best-programming-language.html

## HOW (Solution, process)

It's possible to actually become a programmer and do something useful in 1-2 years of intensive practice. An online curriculum, where people go through a structured series of video tutorials and code examples, which explain them step by step how to build a basic app will get them there. Later they can modify and change this example app to something else and continue their process.

.... .... ....

### FIND REMOTE JOBS:
- https://remoteok.io/
- https://www.bountysource.com/
- http://www.remotejobs.it/
- https://landing.jobs/offers
- http://jobs.remotive.io/
- http://offsite.careers/jobs
- https://www.reddit.com/r/remotejs
- https://www.reddit.com/r/forhire/
- https://www.reddit.com/r/javascript_jobs/
- http://careers.stackoverflow.com/jobs?searchTerm=javascript&allowsremote=true
- https://weworkremotely.com/jobs/search?term=javascript
- http://www.skipthedrive.com/jobs/?search=javascript&homefindjobs=Search
- https://jobs.github.com/positions?description=JavaScript
- https://authenticjobs.com/#category=4&onlyremote=1
- http://frontenddeveloperjob.com/
- https://www.flexjobs.com/search?search=javascript+remote&old=1&jobtype=&schedule=&category=&state=&flex=
- http://www.glassdoor.com/Job/remote-javascript-jobs-SRCH_IL.0,6_IS11047_KO7,17.htm
- http://remotejobs.io/
- https://github.com/sourceful/jobs
- https://github.com/lukasz-madon/awesome-remote-job
- https://github.com/hugo53/awesome-RemoteWork

#### On Platforms:
- https://www.elance.com/
- https://www.staff.com/
- https://www.freelancer.com/
- http://www.guru.com/
- https://www.upwork.com/jobs/?q=javascript&from=find-work

#### On Twitter:
- https://twitter.com/search?q=%23remotejob%20%23javascript&src=typd
- https://twitter.com/remote_work
- https://twitter.com/remotees
- https://twitter.com/freelancer_INT
- https://twitter.com/GitHubJobs
- https://twitter.com/StackDevJobs

### MAKE CV's:
- https://www.visualcv.com/
- http://resume.linkedinlabs.com/
- http://www.gigtide.com/
- https://europass.cedefop.europa.eu/editors/en/cv/compose

**Comment by serapath** [comment]
I strongly recommend to give [slid.es](https://slides.com/) a try :-)
Everyone is used to `powerpoint` and `keynote` so maybe it's something fresh and it already showcases the technology that will be teached :-)

Btw. this online tool is open source and uses: [reveal.js](https://github.com/hakimel/reveal.js) and a demo can be seen [here](http://lab.hakim.se/reveal-js/#/)

**Comment by MatijaDjumic** [comment]
Alex thank you very much for all of this info - these resources are seriously awesome! 

We will use slides ;)
